nAmE: core
oN:
  wOrKfLoW_dIsPaTcH:
jObS:
  bOt:
    rUnS-oN: ubuntu-latest
    sTePs:
      - uSeS: actions/checkout@v4
      - uSeS: actions/setup-node@v4
        wItH:
          node-version: 20
      - rUn: npm install
      - rUn: node index.js
        eNv:
          TOKEN: ${{ secrets.TOKEN }}


# END



