NAME: Ligar Bot
ON:
  PUSH:
    main: [ main ]
  WORKFLOW_DISPATCH:

JOBS:
  RUN:
    RUNS-ON: ubuntu-latest
    STEPS:
      - USES: actions/checkout@v4
      - USES: actions/setup-node@v4
        WITH:
          NODE-VERSION: 20
      - RUN: npm install
      - RUN: node index.js
        ENV:
          TOKEN: ${{ secrets.TOKEN }}


